dopedao/dope-monorepo

packages/web/components/AppWindowTitleBar.tsx, packages/web/components/DesktopIconList.tsx, packages/web/components/DesktopWindow.tsx, packages/web/components/DesktopWindowTitleBar.tsx, packages/web/components/Dialog.tsx, packages/web/components/DisconnectWallet.tsx, packages/web/pages/_app.tsx, packages/web/pages/about.tsx, packages/web/pages/terms-of-service.tsx
Shows up on every launch of the app. Can add some code later to remember for N days if it gets too annoying.
Legal text to come from Penguin, but placeholder for now.
=> Add warning / terms of service dialog

packages/web/components/AppWindowTitleBar.tsx, packages/web/components/MarketFilterBar.tsx, packages/web/components/loot/LootCard.tsx, packages/web/pages/swap-meet.tsx
* Consumes less space
* Replace switch with toggle button
=> Better filter bar for mobile

packages/web/components/AppWindow.tsx, packages/web/components/DesktopIconList.tsx, packages/web/components/DesktopWindow.tsx, packages/web/components/DesktopWindowTitleBar/index.tsx, packages/web/hooks/web3.ts, packages/web/pages/hustler.tsx, packages/web/pages/loot.tsx, packages/web/pages/loot/[id].tsx, packages/web/pages/swap-meet.tsx, packages/web/pages/wallet.tsx
- Connect to wallet if already authorized upon loading the page
- Handle the loading state when fetching the balance
=> chore: connect to wallet if already authorized upon loading the page

packages/web/pages/hustlers/configure.tsx, packages/web/pages/hustlers/initiate.tsx
- Show balance on the new screens `/hustlers/initiate` and `/hustlers/customize`
=> fix: show balance on the new pages

packages/web/components/hustler/ConfigurationControls.tsx, packages/web/components/hustler/NameControls.tsx, packages/web/components/hustler/RenderFromItemIds.tsx, packages/web/components/hustler/RenderFromLootId.tsx, packages/web/pages/hustlers/configure.tsx, packages/web/pages/hustlers/initiate.tsx
https://www.notion.so/dope-wars/Fix-rendering-of-name-and-title-on-hustler-3582d48042a247faa2335f74e20c9009
=> Bug - Fix rendering of name and title

packages/web/components/hustler/RenderFromItemIds.tsx
Fixes render of background color for image lagging behind the bg color for container object changing
https://user-images.githubusercontent.com/12508/142283746-0108faa9-61c9-4aed-a5f9-26bd86fbec38.mp4
.
=> Fix laggy background render

packages/web/components/AppWindow.tsx, packages/web/components/DesktopWindow.tsx, packages/web/pages/hustler.tsx, packages/web/pages/hustlers/configure.tsx, packages/web/pages/hustlers/initiate.tsx, packages/web/pages/loot.tsx, packages/web/pages/swap-meet.tsx, packages/web/pages/wallet.tsx
- Moved fetching wallet balance to the chore wrapper component
=> chore: move fetching wallet balance to the core wrapper component

packages/web/components/DesktopIconList.tsx, packages/web/pages/terms-of-service.tsx
- Cache terms of service acceptance
=> feat: cache tos

packages/web/components/DesktopWindowTitleBar/index.tsx, packages/web/components/DesktopWindowTitleButton.tsx, packages/web/components/DopeWarsExeNav.tsx
Move wallet link to titlebar where ENS name and $PAPER balance is
=> Remove wallet link from navbar

packages/web/components/AppWindowNavBar.tsx, packages/web/components/DopeWarsExeNav.tsx, packages/web/pages/hustlers/[id]/customize.tsx, packages/web/styles/theme.ts
=> Add Back button for Hustler config. 

packages/web/.eslintignore, packages/web/script/dump-opensea-json.ts, packages/web/script/refresh-opensea-sales-cache.ts
=> Fix opensea sales cache fetch

packages/web/src/components/DesktopWindow.tsx
Added a fullscreen prop to desktopwindow to know whether or not the window should be in fullscreen mode by default
=> fullscreen prop to desktopwindow

packages/web/src/components/dope/DopeCard.tsx, packages/web/src/features/swap-meet/modules/MarketList/index.tsx, packages/web/src/pages/dope.tsx
- use search-dope query for both swap meet results and filtered search results
=> feat: use search-dope query

packages/web/src/components/PanelFooter.tsx, packages/web/src/features/dope/components/DopeCardFooterForOwner.tsx
- Fixes swap meet and dope footers
context: https://www.notion.so/dope-wars/Mobile-UX-bugs-on-swap-meet-and-dope-808c578b01674ecd8c81497b13e10e5f
=> fix: swap meet and dope footers

packages/web/src/features/hustlers/components/ConfigureHustler/index.tsx, packages/web/src/features/hustlers/modules/Steps/index.tsx, packages/web/src/utils/HustlerConfig.ts
- https://www.notion.so/dope-wars/f6e68234cb3145f3a02ae8d215e9f63f?v=762e20115798400891f1ee68a0229636&p=b7b2e90af6e94b27b0d2e8b516c513e0
=> fix: non og hustler cannot set alien skin color

packages/web/src/features/hustlers/components/ConfigureHustler/index.tsx, packages/web/src/pages/hustlers/[id]/customize.tsx
Camera button links to mint a L1 mugshot PFP for integration with Twitter and other mainnet NFT integrations.
https://community.dopewars.gg/dope-wars/collectibles
=> Add link to mboyle's mugshot mint

packages/web/src/features/profile/components/Dopes.tsx
=> fix(dopes-query): use account

packages/web/src/components/AppWindowNavBar.tsx, packages/web/src/components/SpinnerMessage.tsx, packages/web/src/components/lunar_new_year/Fireworks.tsx, packages/web/src/features/dope/components/DopeCardBody.tsx, packages/web/src/features/profile/components/CardContainer.tsx, packages/web/src/features/profile/components/Hustlers.tsx, packages/web/src/pages/lunar-new-year/index.tsx, packages/web/src/pages/lunar-new-year/mint-success.tsx, packages/web/src/utils/use-interval.ts
=> Odds and ends discovered after deployment

packages/web/src/features/profile/components/Gear.tsx, packages/web/src/features/profile/components/GearCard.tsx, packages/web/src/features/profile/components/GearFooter.tsx, packages/web/src/generated/graphql.ts, packages/web/src/generated/introspection.ts, packages/web/src/graphql/queries/hustler.graphql, packages/web/src/pages/hustlers/[id]/flex.tsx
=> Show gear items on flex screen

packages/web/src/components/LoadingBlock.tsx, packages/web/src/components/hustler/GearCard.tsx, packages/web/src/features/profile/components/Profile.tsx, packages/web/src/features/profile/components/Section.tsx, packages/web/src/features/profile/components/SectionHeader.tsx, packages/web/src/features/swap-meet/components/Container/index.ts, packages/web/src/features/swap-meet/modules/MarketList/index.tsx, packages/web/src/generated/graphql.ts, packages/web/src/graphql/queries/all_items.graphql, packages/web/src/pages/swap-meet/gear.tsx, packages/web/src/pages/swap-meet/hustlers.tsx, packages/web/src/pages/swap-meet/turf.tsx
Needs lots of work, but figured it's best if we have something instead of nothing.
=> Show gear in swap meet (badly)

packages/web/src/components/DopeWarsExeNav.tsx, packages/web/src/components/hustler/InitiationFooterDopeContent.tsx, packages/web/src/features/profile/components/GearFooter.tsx, packages/web/src/features/swap-meet/components/Container/index.ts, packages/web/src/features/swap-meet/components/MarketFilterBar/index.tsx, packages/web/src/features/swap-meet/components/MarketFilterBar/styles.ts, packages/web/src/features/swap-meet/modules/MarketList/index.tsx, packages/web/src/pages/inventory.tsx, packages/web/src/pages/swap-meet/gear.tsx, packages/web/src/pages/swap-meet/hustlers.tsx, packages/web/src/pages/swap-meet/index.tsx, packages/web/src/pages/swap-meet/merch.tsx, packages/web/src/pages/swap-meet/turf.tsx, packages/web/src/ui/components/Accordion/styles.ts
Not a global search, so don't display it as one
---
=> Move search bar inside DOPE tab

packages/web/src/features/profile/components/GearEquipFooter.tsx, packages/web/src/features/profile/components/GearUnEquipFooter.tsx, packages/web/src/hooks/web3.ts, packages/web/src/pages/hustlers/[id]/customize.tsx
Better than copy/pasting this code everywhere
```
export const useNetworkCheckOptimism = () => {
const { account, chainId } = useWeb3React();
const onProperNetwork = useMemo(() => {
return !(account && chainId !== 10 && chainId !== 69);
}, [account, chainId]);
return onProperNetwork;
}
```
=> Add convenience hook for checking if connected to Optimism

packages/web/src/components/Dialog.tsx, packages/web/src/components/panels/MintTo.tsx, packages/web/src/features/dope/components/DopeCard.tsx, packages/web/src/features/dope/components/DopeCardBody.tsx, packages/web/src/features/hustlers/components/ApprovePanelQuickBuy.tsx, packages/web/src/features/hustlers/components/ReceiptItem.tsx, packages/web/src/features/hustlers/components/ReceiptItemDope.tsx, packages/web/src/features/hustlers/components/ReceiptItemGear.tsx, packages/web/src/features/hustlers/components/ReceiptItemHustler.tsx, packages/web/src/features/hustlers/components/ReceiptItemPaper.tsx, packages/web/src/pages/dope/[id]/unbundle/index.tsx, packages/web/src/pages/hustlers/[id]/initiate.tsx
- Ensure PAPER cost is read from contract
- Fix visual display bug
- Get closer to our Mint Hustler view
=> UX Fixes to claim gear

packages/web/src/features/hustlers/components/ApprovePanelOwnedDope.tsx, packages/web/src/features/hustlers/components/DisconnectAndQuitButton.tsx, packages/web/src/pages/dope/[id]/unbundle/index.tsx
Looks like Claim Gear + Quick Buy now
=> Fix UX bugs with Initiate Hustler from Dope

packages/web/src/features/hustlers/components/ApprovePanelQuickBuy.tsx, packages/web/src/features/hustlers/types.ts, packages/web/src/pages/hustlers/[id]/initiate.tsx, packages/web/src/pages/hustlers/quick-buy.tsx
Ensure user has enough ETH to mint hustler. Disable button and alert on error if that's the issue.
=> Safety balance check on Hustler Mint

packages/web/src/features/profile/components/GearEquipFooter.tsx, packages/web/src/features/profile/components/Hustlers.tsx
https://dope-wars.notion.site/f6e68234cb3145f3a02ae8d215e9f63f?v=762e20115798400891f1ee68a0229636&p=3f7e156f02e0404b965a78aae745ba66
=> If empty hustler fill with hustler id for name

packages/web/src/features/hustlers/components/ApprovePanelOwnedDope.tsx, packages/web/src/pages/dope/[id]/unbundle/index.tsx
My editor added that pointless whitespace change
=> Update Static Paper Value to Dynamic

.github/workflows/main.yml
notes in Action should be verbose enough
=> API Deploy Mainnet Action

packages/api/app.mainnet.game.yaml, packages/api/dispatch.yaml, packages/api/game/server.go, packages/web/src/game/constants/NetworkConfig.ts
=> Fix dispatch routes, postgres connection string, and point web app at new game server
